### ISSUE TITLE
You can try using the custom domain option in netlify

### ISSUE THREAD

**Issue by ShimilSAbraham** [apoorvpandey0/30daysofscam-html#14]
that way the link would look more meaningful like '30daysofscam.netlify.app

**Comment by apoorvpandey0** [comment]
Oh that's possible? coool!
I think but this URL is widely shared already now, is there a way to forward from current url to new one

**Comment by ShimilSAbraham** [comment]
Yes domain name can be changed anytime on netlify.. lemme see if i can send u a pic

**Comment by ShimilSAbraham** [comment]
![Screenshot 2021-10-06 004541](https://user-images.githubusercontent.com/62107737/136088310-c3fdc646-c202-4921-b5d1-1e766e5b29d3.png)

Later you will have an option to add custom domain name to the site

**Comment by ShimilSAbraham** [comment]
If i can, i will try making some contribution for the desktop view (>1380px)
