### ISSUE TITLE
Add 2 memes and make changes in CSS styling

### ISSUE THREAD

**Issue by Dishant145** [apoorvpandey0/30daysofscam-html#9]
Hi! I am a participant in Hacktoberfest 2021!

I have contributed to this repo by adding 2 new memes and making some changes in the CSS Styling!

Please review and if you feel the changes are minimal or it has changed the structure of the website, please do tell:) 

Would definitely change them again!

Thanks:)

**Comment by apoorvpandey0** [comment]
It's great!
